### ISSUE TITLE
expect fails on integers

### ISSUE THREAD

**Issue by jolle-c** [bfad/lspec#3]
I get this error
Definition Not Found: expect(integer)
when running this test
expect(#msgArray -> isa(::array))
# msgArray -> isa(::array) will return 1 when it's true.

**Comment by bfad** [comment]
This is a feature, not a bug. You must pass a boolean to expect.

Here are a couple of different workarounds. First, since the ->isA method can also return 2 or 3 depending on if it's an sub-type or a trait, you could continue to use it doing one of the following:

```
expect(#msgArray->isa(::array) > 0)
expect(boolean(#msgArray->isa(::array)))
```

If you are checking the actual type of `#msgArray` and not if it might be a sub-type or a trait, then I recommend you do this:

```
expect(::array, #msgArray->type)
```

After I typed the above, I realized that this would be a good candidate for an expectation. If you do want to check for if it is a sub-type or trait (or type), I have add the following expectation:

```
expect->valueIsA(#msgArray, ::array)
```

This is in commit 99b0087f518e109bd132217969dd116e950ee30b. If you look at the source code, you'll see other expectations such as `expect->null`, `expect->error`, and `expect->errorCode`. If you run into anything you thing should be added, feel free to create tests and code for them and submit a pull request. (For tests, see lspec / tests / lspec_expectations.test.inc)
